#aplicacion en express.js - react.js - mongodb
#
version: '3'
services:
  backend:
    restart: always
    build: ./backend
    ports:
      - 4000:4000
    depends_on: 
      - mongo-sueldos
    volumes:
      - ./backend:/backend
  frontend:
    build: ./frontend
    ports:
      - 4001:4001
    volumes:
      - ./frontend:/app/
  mongo-sueldos:
    image: mongo
    logging:
        driver: none
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
