#aplicacion en express.js - react.js - mongodb
#
version: '3'
services:
  node:
    restart: always
    build: ./backend
    ports:
      - 4000:8080
    volumes:
      - ./backend:/backend
  react:
    build: ./frontend
    ports:
      - 4001:8081
    volumes:
      - ./frontend:/frontend
  mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
